import { verifyFirebaseToken } from "../../../lib/ai/auth-server";
import { fileConfig, fileKindForMime } from "../../../lib/files/config";
import { deleteFromImageKit, uploadToImageKit } from "../../../lib/imagekit/server";
import { deleteUserFile, listUserFiles, saveUserFile } from "../../../lib/files/service";
import { getUserFile } from "../../../lib/files/service";

export const runtime = "nodejs";
function authToken(request: Request) { const header = request.headers.get("authorization"); if (!header?.startsWith("Bearer ")) throw new Error("UNAUTHORIZED"); return header.slice(7).trim(); }
function failure(error: unknown, fallback: string) { if (error instanceof Error && error.message === "UNAUTHORIZED") return Response.json({ error: "Please log in to manage files." }, { status: 401 }); console.error("Gold AI file API failed", { error: error instanceof Error ? error.message : "unknown error" }); return Response.json({ error: fallback }, { status: 503 }); }
export async function GET(request: Request) { try { const uid = await verifyFirebaseToken(authToken(request)); return Response.json({ files: await listUserFiles(uid) }); } catch (error) { return failure(error, "Unable to load your files right now."); } }
export async function POST(request: Request) { try { const uid = await verifyFirebaseToken(authToken(request)); const form = await request.formData(); const file = form.get("file"); if (!(file instanceof File)) return Response.json({ error: "Choose a file first." }, { status: 400 }); const kind = fileKindForMime(file.type); if (!kind) return Response.json({ error: "Unsupported file type." }, { status: 400 }); const limit = kind === "image" ? fileConfig.maxImageSize : fileConfig.maxDocumentSize; if (file.size > limit) return Response.json({ error: "File is too large to upload." }, { status: 413 }); const fileId = crypto.randomUUID(); const uploaded = await uploadToImageKit(file, uid, fileId); const saved = await saveUserFile(uid, { fileName: file.name.replace(/[^a-zA-Z0-9._-]/g, "_"), fileType: kind, mimeType: file.type, size: file.size, ...uploaded }); return Response.json({ file: saved }, { status: 201 }); } catch (error) { return failure(error, "Unable to upload this file right now."); } }
export async function DELETE(request: Request) { try { const uid = await verifyFirebaseToken(authToken(request)); const id = new URL(request.url).searchParams.get("id"); if (!id) return Response.json({ error: "File not found." }, { status: 400 }); const file = await getUserFile(uid, id); if (!file) return Response.json({ error: "File not found." }, { status: 404 }); if (file.imageKitFileId) await deleteFromImageKit(file.imageKitFileId); await deleteUserFile(uid, id); return Response.json({ success: true }); } catch (error) { return failure(error, "Unable to delete this file right now."); } }
