"use client";

import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, File, Trash2, Upload } from "lucide-react";
import Link from "next/link";
import { AppHeader, GoldAILogoLoader, MobileBottomNav } from "./gold-ai-ui";
import { getFirebaseServices } from "../lib/firebase";
import type { UserFile } from "../types/files";

export function FilesWorkspace() {
  const [files, setFiles] = useState<UserFile[]>([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [error, setError] = useState<string | null>(null);
  const token = useCallback(async () => { const value = await getFirebaseServices().auth.currentUser?.getIdToken(); if (!value) throw new Error("Please log in again."); return value; }, []);
  const load = useCallback(async () => { try { const response = await fetch("/api/files", { headers: { Authorization: `Bearer ${await token()}` } }); const data = await response.json() as { files?: UserFile[]; error?: string }; if (!response.ok) throw new Error(data.error || "Unable to load files."); setFiles(data.files || []); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load files."); } finally { setLoading(false); } }, [token]);
  useEffect(() => { const timeoutId = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timeoutId); }, [load]);
  async function upload(file: File) { setUploading(true); setError(null); try { const form = new FormData(); form.append("file", file); const response = await fetch("/api/files", { method: "POST", headers: { Authorization: `Bearer ${await token()}` }, body: form }); const data = await response.json() as { file?: UserFile; error?: string }; if (!response.ok || !data.file) throw new Error(data.error || "Unable to upload file."); setFiles((items) => [data.file!, ...items]); } catch (uploadError) { setError(uploadError instanceof Error ? uploadError.message : "Unable to upload file."); } finally { setUploading(false); } }
  async function remove(file: UserFile) { if (!window.confirm(`Delete ${file.fileName}?`)) return; try { const response = await fetch(`/api/files?id=${encodeURIComponent(file.id)}`, { method: "DELETE", headers: { Authorization: `Bearer ${await token()}` } }); if (!response.ok) throw new Error("Unable to delete file."); setFiles((items) => items.filter((item) => item.id !== file.id)); } catch (removeError) { setError(removeError instanceof Error ? removeError.message : "Unable to delete file."); } }
  return <div className="files-route"><AppHeader onMenu={() => undefined} backToHome /><main className="files-main"><Link className="files-back" href="/"><ArrowLeft size={16} /> Home</Link><header className="files-heading"><span className="eyebrow">Your private library</span><h1>My Files</h1><p>Upload images and documents to use with Gold AI.</p></header><label className="files-upload"><Upload size={18} /><span>{uploading ? "Uploading..." : "Choose an image or document"}</span><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain" disabled={uploading} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); event.currentTarget.value = ""; }} /></label>{error && <p className="form-error" role="alert">{error}</p>}{loading ? <GoldAILogoLoader size="md" label="Loading files..." /> : files.length === 0 ? <div className="files-empty"><File size={24} /><h2>No files yet</h2><p>Upload an image or document to get started.</p></div> : <section className="files-grid">{files.map((file) => <article className="file-card" key={file.id}>{file.fileType === "image" ? <img src={file.thumbnailUrl || file.url} alt={file.fileName} /> : <span className="file-card-icon"><File size={26} /></span>}<div><strong>{file.fileName}</strong><small>{file.mimeType} · {Math.ceil(file.size / 1024)} KB</small></div><button className="icon-button" type="button" onClick={() => void remove(file)} aria-label={`Delete ${file.fileName}`} title="Delete file"><Trash2 size={16} /></button></article>)}</section>}</main><MobileBottomNav /></div>;
}
