"use client";

import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, Building2, Copy, Mail } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { AppHeader, MobileBottomNav } from "./gold-ai-ui";
import { getFirebaseServices } from "../lib/firebase";
import type { Organization, OrganizationCreditAccount, OrganizationMember, OrganizationInvitation } from "../types/organization";

export function OrganizationDashboard() {
  const params = useParams<{ organizationId: string }>(); const organizationId = params.organizationId;
  const [organization, setOrganization] = useState<Organization | null>(null); const [member, setMember] = useState<OrganizationMember | null>(null); const [credits, setCredits] = useState<OrganizationCreditAccount | null>(null); const [invitations, setInvitations] = useState<OrganizationInvitation[]>([]);
  const [email, setEmail] = useState(""); const [role, setRole] = useState("member"); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const token = useCallback(async () => { const value = await getFirebaseServices().auth.currentUser?.getIdToken(); if (!value) throw new Error("Please log in again."); return value; }, []);
  const load = useCallback(async () => { try { const response = await fetch(`/api/organizations/${encodeURIComponent(organizationId)}`, { headers: { Authorization: `Bearer ${await token()}` } }); const data = await response.json() as { organization?: Organization; member?: OrganizationMember; credits?: OrganizationCreditAccount; error?: string }; if (!response.ok || !data.organization) throw new Error(data.error || "Unable to load organization."); setOrganization(data.organization); setMember(data.member || null); setCredits(data.credits || null); const invitationResponse = await fetch("/api/organizations/invitations", { headers: { Authorization: `Bearer ${await token()}` } }); if (invitationResponse.ok) { const invitationData = await invitationResponse.json() as { invitations?: OrganizationInvitation[] }; setInvitations((invitationData.invitations || []).filter((item) => item.organizationId === organizationId)); } } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load organization."); } finally { setLoading(false); } }, [organizationId, token]);
  useEffect(() => { const timeoutId = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timeoutId); }, [load]);
  async function invite() { if (!email.trim()) { setError("Add an email address."); return; } setError(null); setNotice(null); try { const response = await fetch("/api/organizations/invitations", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await token()}` }, body: JSON.stringify({ organizationId, email, role }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "Unable to invite this user."); setEmail(""); setNotice("Invitation created."); } catch (inviteError) { setError(inviteError instanceof Error ? inviteError.message : "Unable to invite this user."); } }
  return <div className="organization-route"><AppHeader onMenu={() => undefined} backToHome /><main className="organization-main">{loading ? <p className="transactions-empty">Loading organization...</p> : organization && <><Link className="organization-back" href="/organizations"><ArrowLeft size={16} /> Organizations</Link><header className="organization-heading"><span className="organization-icon large"><Building2 size={25} /></span><div><span className="eyebrow">{member?.role || "Member"} workspace</span><h1>{organization.name}</h1><p>{organization.type} · {organization.country || "Africa-wide"} · {organization.currency}</p></div></header><div className="organization-stats"><article><span>Members</span><strong>Available in dashboard</strong></article><article><span>Organization credits</span><strong>{credits?.balance ?? 0}</strong></article><article><span>Status</span><strong>{organization.status}</strong></article></div>{member && ["owner", "admin"].includes(member.role) && <section className="organization-invite"><div className="section-title"><div><span className="eyebrow">Member management</span><h2>Invite a member</h2></div><Mail size={20} /></div><div className="organization-invite-form"><input value={email} onChange={(event) => setEmail(event.target.value)} type="email" placeholder="person@example.com" aria-label="Invitee email" /><select value={role} onChange={(event) => setRole(event.target.value)} aria-label="Member role"><option value="member">Member</option><option value="manager">Manager</option><option value="admin">Admin</option></select><button className="auth-submit" type="button" onClick={() => void invite()}>Invite</button></div>{notice && <p className="form-success" role="status">{notice}</p>}{error && <p className="form-error" role="alert">{error}</p>}</section>}{invitations.length > 0 && <section className="organization-invitations"><div className="section-title"><div><span className="eyebrow">Pending invitations</span><h2>Invitations for you</h2></div><Copy size={20} /></div>{invitations.map((invitation) => <p key={invitation.id}>{invitation.email} · {invitation.role} · pending</p>)}</section>}</>}</main><MobileBottomNav /></div>;
}
