"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Building2, Plus, Users } from "lucide-react";
import Link from "next/link";
import { AppHeader, MobileBottomNav } from "./gold-ai-ui";
import { getFirebaseServices } from "../lib/firebase";
import type { Organization } from "../types/organization";
import { organizationTypeOptions } from "../lib/organization/config";

export function OrganizationsWorkspace() {
  const router = useRouter();
  const [organizations, setOrganizations] = useState<Organization[]>([]);
  const [name, setName] = useState(""); const [type, setType] = useState("school"); const [country, setCountry] = useState("");
  const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const token = useCallback(async () => { const value = await getFirebaseServices().auth.currentUser?.getIdToken(); if (!value) throw new Error("Please log in again."); return value; }, []);
  const load = useCallback(async () => { try { const response = await fetch("/api/organizations", { headers: { Authorization: `Bearer ${await token()}` } }); const data = await response.json() as { organizations?: Organization[]; error?: string }; if (!response.ok) throw new Error(data.error || "Unable to load organizations."); setOrganizations(data.organizations || []); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load organizations."); } finally { setLoading(false); } }, [token]);
  useEffect(() => { const id = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(id); }, [load]);
  async function create() { if (!name.trim()) { setError("Add an organization name."); return; } setCreating(true); setError(null); try { const response = await fetch("/api/organizations", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await token()}` }, body: JSON.stringify({ name, type, country: country || undefined, currency: "UGX" }) }); const data = await response.json() as { organization?: Organization; error?: string }; if (!response.ok || !data.organization) throw new Error(data.error || "Unable to create organization."); router.push(`/organizations/${data.organization.id}`); } catch (createError) { setError(createError instanceof Error ? createError.message : "Unable to create organization."); } finally { setCreating(false); } }
  return <div className="organizations-route"><AppHeader onMenu={() => undefined} backToHome /><main className="organizations-main"><header className="organizations-heading"><span className="eyebrow">Personal and shared workspaces</span><h1>Your Organizations</h1><p>Create or open a secure organization workspace.</p></header><section className="organizations-layout"><div className="organization-list-panel"><div className="section-title"><div><span className="eyebrow">Workspaces</span><h2>{organizations.length ? "Your organizations" : "No organizations yet"}</h2></div><Users size={20} /></div>{loading ? <p className="transactions-empty">Loading organizations...</p> : organizations.length === 0 ? <p className="transactions-empty">Create an organization to collaborate with your team.</p> : <div className="organization-list">{organizations.map((organization) => <Link className="organization-list-item" href={`/organizations/${organization.id}`} key={organization.id}><span className="organization-icon"><Building2 size={20} /></span><span><strong>{organization.name}</strong><small>{organization.type} · {organization.currency}</small></span><span className="quick-arrow">↗</span></Link>)}</div>}</div><form className="organization-create-panel" onSubmit={(event) => { event.preventDefault(); void create(); }}><span className="section-kicker"><Plus size={14} /> New workspace</span><h2>Create Organization</h2><label>Organization name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. ABC School" /></label><label>Organization type<select value={type} onChange={(event) => setType(event.target.value)}>{organizationTypeOptions.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label>Country <span className="create-optional">Optional</span><input value={country} onChange={(event) => setCountry(event.target.value)} placeholder="e.g. Uganda" /></label><button className="auth-submit" type="submit" disabled={creating}>{creating ? "Creating..." : "Create Organization"}</button>{error && <p className="form-error" role="alert">{error}</p>}</form></section></main><MobileBottomNav /></div>;
}
