import { z } from "zod";
import { verifyFirebaseToken } from "../../../../lib/ai/auth-server";
import { acceptInvitation, createInvitation, getOrganizationAccess, listUserInvitations } from "../../../../lib/organization/service";
import { isOrganizationRole } from "../../../../lib/organization/config";
import { getFirebaseAdmin } from "../../../../lib/firebase-admin";

export const runtime = "nodejs";
function token(request: Request) { const authorization = request.headers.get("authorization"); if (!authorization?.startsWith("Bearer ")) throw new Error("UNAUTHORIZED"); return authorization.slice(7).trim(); }
const inviteSchema = z.object({ organizationId: z.string().min(1), email: z.string().email(), role: z.string() });
export async function GET(request: Request) { try { const uid = await verifyFirebaseToken(token(request)); const user = await getFirebaseAdmin().auth.getUser(uid); return Response.json({ invitations: await listUserInvitations(user.email || "") }); } catch (error) { if (error instanceof Error && error.message === "UNAUTHORIZED") return Response.json({ error: "Please log in to continue." }, { status: 401 }); return Response.json({ error: "Unable to load invitations right now." }, { status: 503 }); } }
export async function POST(request: Request) { try { const uid = await verifyFirebaseToken(token(request)); const parsed = inviteSchema.safeParse(await request.json()); if (!parsed.success || !isOrganizationRole(parsed.data.role) || parsed.data.role === "owner") return Response.json({ error: "Choose a valid member role." }, { status: 400 }); const access = await getOrganizationAccess(uid, parsed.data.organizationId); if (!access.organization || !access.member || !["owner", "admin"].includes(access.member.role)) return Response.json({ error: "You are not authorized to invite members." }, { status: 403 }); return Response.json({ invitation: await createInvitation(parsed.data.organizationId, uid, parsed.data.email, parsed.data.role) }, { status: 201 }); } catch (error) { if (error instanceof Error && error.message === "UNAUTHORIZED") return Response.json({ error: "Please log in to continue." }, { status: 401 }); console.error("Gold AI organization invitation failed", { error: error instanceof Error ? error.message : "unknown error" }); return Response.json({ error: "Unable to create this invitation right now." }, { status: 503 }); } }
export async function PATCH(request: Request) { try { const uid = await verifyFirebaseToken(token(request)); const body = await request.json() as { organizationId?: string; invitationId?: string }; if (!body.organizationId || !body.invitationId) return Response.json({ error: "Invitation not found." }, { status: 400 }); const user = await getFirebaseAdmin().auth.getUser(uid); const member = await acceptInvitation(uid, user.email || "", body.invitationId, body.organizationId); return member ? Response.json({ member }) : Response.json({ error: "This invitation is invalid, expired, or already accepted." }, { status: 400 }); } catch (error) { if (error instanceof Error && error.message === "UNAUTHORIZED") return Response.json({ error: "Please log in to continue." }, { status: 401 }); return Response.json({ error: "Unable to accept this invitation right now." }, { status: 503 }); } }
